[build]
target = "thumbv6m-none-eabi"

[target.thumbv6m-none-eabi]
runner = "probe-rs run --chip RP2040 --protocol swd"
rustflags = [
    "-C", "link-arg=-Tlink.x",
    "-C", "link-arg=-Tlink-rp.x",
    "-C", "link-arg=-Tdefmt.x",
    "-C", "no-vectorize-loops"
]

[env]
DEFMT_LOG = "debug"
